server:
  port: 8080
spring:
  datasource:
    druid:
      url: jdbc:mysql://lynwood.wunian7yulian.top:3306/smp_roles?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: Zhaowentao123!
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      filters: stat
      filter:
        # 慢SQL记录(sql语句执行时间超过某个界限就记录下来)
        stat:
          slow-sql-millis: 200
          log-slow-sql: true

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        allow:
        deny:
  # Redis
  redis:
    host: 127.0.0.1
    password:
    # 数据库索引 默认0
    database: 0
    port: 6379
    # 超时时间 Duration类型 3秒
    timeout: 3S
mybatis-plus:
#  mapper-locations: classpath*:*mapper/xml/*Mapper.xml
  mapper-locations: classpath:/com/dyd/ssp/smp/mapper/xml/*Mapper.xml
  type-aliases-package: com.dyd.ssp.smp.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:config/logback-spring.xml
  level:
    root: info
  path: logs/
  file: dyd-ssp-smp.log


# 忽略鉴权url
ignored:
  urls:
    - /smp/dictData/getByType/**
    - /smp/auth/register
    - /smp/common/**
    - /druid/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /test/**

smp:
  # 全局限流
  rateLimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 总限制100个请求
    limit: 100
  # token交互方式
  token:
    # 默认JWT 启用Redis后设置为true后，token将存入redis，并具有单点登录功能
    redis: true
  # token过期时间（分钟）
  tokenExpireTime: 60
  # 用户选择保存登录状态对应token过期时间（天）
  saveLoginTime: 7
  # 限制用户登陆错误次数（次）
  loginTimeLimit: 5
  # 错误超过次数后多少分钟后才能继续登录（分钟）
  loginAfterTime: 10
  # ES
  elasticsearch:
    nodeClient: 127.0.0.1:9200
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
  logRecord:
    es: false
